Отделка пола: Добавление функционала по заведению контура в дверные проемы
Bim4Everyone/ARExtensions pull request #10
Opened 2024-01-16 08:13 UTC by DiBrainz

Добавлен функционал по заведению контура в дверные проемы
![image](https://github.com/Bim4Everyone/ARExtensions/assets/103031576/ae1f7f51-8835-4174-9439-e2eb858e556f)
GUI расширен для настройки заведения контура в проемы
1. Добавлена настройка заведения в дверные проемы (не заводить либо заводить и каким образом)
![image](https://github.com/Bim4Everyone/ARExtensions/assets/103031576/82fe97c8-9e8a-48b5-a87f-8d90c3642760)
2. Добавлен выбор как именно заводить перекрытие с разным открыванием двери для варианта заведения на всю толщину стены (работает только с настроенными семействами), а также справка для пользователя
![image](https://github.com/Bim4Everyone/ARExtensions/assets/103031576/52236726-7493-43ad-86af-2a617048f58d)

2024-06-07 09:19 UTC, vlastroG requested changes
На дефолтном файле автодеска RAC_basic_sample_project в 2022 ревите не создаются отделочные перекрытия в помещениях, посмотри в чем проблема

2024-06-10 08:58 UTC, dosymep requested changes
- удали везде декоратор `@reactive`, там где он не требуется.
- не рекомендую использовать enum, лучше вместо них создать иерархию классов
- рекомендую все операции над дверьми выделить в отдельный класс
- все константы выдели в отдельные переменные и напиши, почему они имеют такое значение
-

2024-06-10 08:58 UTC, dosymep commented on АР.tab/РД.panel/Отделка пола.pushbutton/script.py
> +    def get_solid_from_element(self, element):
Возможно тебе подойдет [метод](https://dosymep.net/dosymep.Revit/api/2024/dosymep.Revit.Geometry.ElementExtensions.html#dosymep_Revit_Geometry_ElementExtensions_GetSolids_Autodesk_Revit_DB_Element_) из платформы?

2024-06-10 08:58 UTC, dosymep commented on АР.tab/РД.panel/Отделка пола.pushbutton/script.py
> +    def get_solid_from_host_walls(self, door):
Возможно тебе подойдет [метод](https://dosymep.net/dosymep.Revit/api/2024/dosymep.Revit.Geometry.SolidExtensions.html#dosymep_Revit_Geometry_SolidExtensions_CreateUnitedSolids_System_Collections_Generic_IList_Autodesk_Revit_DB_Solid__) из платформы?

2024-07-02 05:42 UTC, dosymep approved these changes

2024-07-02 05:42 UTC, merged